DEMOMODE: True
SITE_URL: "http://127.0.0.1:5000"
SITE_TITLE: "A Digital Edition of Harley 2250"
MENU:
  - '<a id="about" href="#">About <span class="sr-only">(current)</span></a>'
  - 'Harley 2250':
    - '<a class="navLink" href="harley2250/martin.xml">Saint Martin</a>'
    - '<a class="navLink" href="harley2250/erkenwald.xml">Saint Erkenwald</a>'
SPLASH: "Select a Text from the Menu"
ABOUT:
  - "title": "About This Site"
  - "message": >
      <p>This is a demonstration of the digital edition
      platform for the Archive of Early Middle English. This version 
      includes material from London, British Library, Harley 2250.This 
      is an alpha version used for development purposes. Any 
      texts currently loaded are incomplete fragments used to test 
      functionality. Image loading time will vary depending on your 
      internet connection.</p><p>Clicking a word will open a dialog and 
      perform a simple search of the Middle English Dictionary, adding a 
      wildcard asterisk to the end of the word. Obviously, this will not 
      always produce the desired results, but eventually words can be 
      matched to MED IDs.</p>
METADATA:
  - "title": "Metadata"
  - "message": >
      <p>Questa funzione non è ancora attiva. E alla fine mostrare il 
      contenuto dal <code>teiHeader</code>.</p>